name: Auto Preprocessing

# Trigger: Workflow berjalan setiap kali kamu push ke branch main
on:
  push:
    branches: [ main ]
    paths:
      - 'rakhadataset_raw/**' # Hanya jalan jika ada perubahan di folder data mentah

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Mengambil kode dari repository ke virtual machine GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Menginstal Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Menginstal library yang dibutuhkan
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy

    # 4. Menjalankan skrip automasi kamu
    - name: Run preprocessing script
      run: python preprocessing/automate_Nama-siswa.py

    # 5. Menyimpan kembali hasil preprocessing ke GitHub
    - name: Commit and push changes
      run: |
        # Gunakan format: git config --local <nama_properti> <nilai>
        git config --local user.email "nuxengt@gmail.com"
        git config --local user.name "rakhadaivanda"
        
        git add preprocessing/namadataset_preprocessing/
        git commit -m "Auto-update preprocessed data [skip ci]" || echo "No changes to commit"
        git push
